version: "3"
services: 
  api:
    build: .
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    # environment: 
    #   - DATABASE_HOSTNAME=localhost
    #   - DATABASE_PORT=5432
    #   - DATABASE_PASSWORD=12345
    #   - DATABASE_USERNAME=josephkaiser
    #   - DATABASE_NAME=fastapi
    #   - SECRET_KEY=FD0CCA14-D8A4-4B73-AE21-093C66D2D0AB
    #   - ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=60