name: Build and Deploy code

on:
  push:
    branches:
      - "main"
      - "anotherbranch"
  pull_request:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubunutu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to joe
        uses: echo "hello joe"