name: Build and Deploy code

on: [push, pull_request]

env:

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 12345
      DATABASE_USERNAME: postgres # for some reason it didnt' like josephkaiser
      DATABASE_NAME: fastapi
      SECRET_KEY: FD0CCA14-D8A4-4B73-AE21-093C66D2D0AB
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubunutu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-verison: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest